### ISSUE TITLE
[MOB] Tiki Target

### ISSUE THREAD

**Issue by Godmatik** [GameFreedomGG/Cataclysm#13]
Tiki Targets follow you when you attack them, they should remain stationary.

![WoWScrnShot_101721_144229](https://user-images.githubusercontent.com/37913400/137642553-4259d570-4b85-4806-a08a-2b3f85b4080b.jpg)

https://cata-twinhead.twinstar.cz/?npc=38038

**Comment by Godmatik** [comment]
They also each give probably double the experience that they should

**Comment by PanJanuszek** [comment]
Tiki target should not give experience :)

**Comment by PanJanuszek** [comment]
Fixed on 04.11.2021
