### ISSUE TITLE
[QUEST] Durotar - Proving Pit - Prevents rest of Troll starting area from being done.

### ISSUE THREAD

**Issue by Godmatik** [GameFreedomGG/Cataclysm#15]
Quest does not work, when attempting to talk to the Darkspear Jailor, and select "I'm ready to face my challenge.", nothing happens.

Thus - can't do rest of troll starting zone quests

https://cata-twinhead.twinstar.cz/?quest=24642

**Comment by PanJanuszek** [comment]
Fixed on 04.11.2021
