### ISSUE TITLE
[QUEST] Durotar - Breaking the Chain

### ISSUE THREAD

**Issue by Godmatik** [GameFreedomGG/Cataclysm#19]
The northwatch lugs should be patrolling while carrying the northwatch supply crates, but they just standing still.

https://cata-twinhead.twinstar.cz/?quest=25167

![WoWScrnShot_101721_163200](https://user-images.githubusercontent.com/37913400/137645687-43849c37-88cd-4c82-ba78-920cef244523.jpg)

**Comment by PanJanuszek** [comment]
Fixed on 05.11.2021
