### ISSUE TITLE
[Hunter trainer durotar] Can't train at the hunter trainer. 

### ISSUE THREAD

**Issue by Faithlolxdd** [GameFreedomGG/Cataclysm#2]
Issue: Can't train at the trainer at the orc/troll starting area. I can accept the quest to learn steady shot, but can't train it. 

How it should work: Should be able to click "Train me." in the dialog with the trainer.

**Comment by 0Raknar0** [comment]
Hey, 

Do you have a whole list with missing trainer dialogs?

**Comment by Godmatik** [comment]
The dialogues are there for the trainers but they just don't work for half of the classes or so.

**Comment by PanJanuszek** [comment]
Fixed 03.11.2021
