### ISSUE TITLE
[Quest] A Job for the Multi-Bot

### ISSUE THREAD

**Issue by CeoOfCoronavirus** [GameFreedomGG/Cataclysm#7]
Issue: The "GS-9x Multi-Bot" that gets assigned to you does not remove the Toxic Geysers in the area when you move close to them. Currently the geysers have Imp models as placeholders.

How to recreate: Do the Quest.

**Comment by CeoOfCoronavirus** [comment]
The Multi-Bot keeps following you around even after abandoning the quest.

**Comment by PanJanuszek** [comment]
Fixed on 04.11.2021
